In [79]:
import numpy as np
import matplotlib.pyplot as plt

In [80]:
Nclass = 500

In [81]:
np.random.randn(Nclass,2)

array([[-2.30127310e-01,  3.22253335e-01],
       [-1.91649729e+00,  4.91582946e-01],
       [-1.12059748e+00,  3.91974802e-01],
       [ 7.88254580e-01,  1.07510965e+00],
       [ 1.02554571e+00, -7.54443396e-01],
       [-1.51782118e+00,  9.68426776e-01],
       [ 2.84529375e-01, -7.60118969e-01],
       [ 4.39300137e-01,  2.52569565e+00],
       [-2.09562755e+00,  4.41893262e-01],
       [-2.53519767e+00, -2.19808380e+00],
       [-1.44192395e-01, -8.90658822e-03],
       [ 1.57325482e+00, -2.77813615e-01],
       [-4.22482315e-01,  1.88768258e+00],
       [-1.84120560e+00, -8.31313631e-01],
       [ 3.33415199e-01,  4.01209160e-04],
       [ 1.05367740e+00, -1.56143830e+00],
       [ 1.24232570e-01,  2.62557183e-01],
       [-1.71607762e+00,  8.15285609e-01],
       [-7.21507420e-01, -1.39004337e+00],
       [-9.15030679e-01, -1.81004834e+00],
       [-1.46967247e+00, -1.10024276e+00],
       [-7.24175676e-01,  2.24232363e-02],
       [-1.43002203e+00, -7.07377204e-01],
       [ 4.

In [82]:
np.array([0,-2])

array([ 0, -2])

In [83]:
X1 = np.random.randn(Nclass,2)+np.array([0,-2]) # adding 0 for all 1st column $ -2 for all 2nd column values
X2 = np.random.randn(Nclass,2)+np.array([2,2])  # adding 2 for all 1st column $ 2 for all 2nd column values
X3 = np.random.randn(Nclass,2)+np.array([-2,2])
X = np.vstack([X1,X2,X3])

In [84]:
X1

array([[-3.37156706e-01, -1.01455774e+00],
       [-2.68207788e+00, -1.17953569e+00],
       [-6.44025739e-02, -1.92132449e+00],
       [ 2.54928818e+00, -1.99343398e+00],
       [ 6.80671961e-02, -2.86967651e+00],
       [-9.47531568e-01, -1.63919005e+00],
       [-6.01178309e-01, -2.37119686e+00],
       [ 1.22876576e-01, -7.25340703e-01],
       [-1.13175779e-01, -1.75235084e+00],
       [-1.68160069e+00, -1.65551507e+00],
       [ 8.24734382e-01, -1.15550543e+00],
       [-1.13722869e+00, -1.76992265e+00],
       [-4.14583355e-01, -1.94287471e+00],
       [-8.50647512e-01, -3.52655310e+00],
       [ 6.58528911e-01, -5.70503714e-01],
       [ 1.95284620e+00, -2.56822371e+00],
       [ 7.12317022e-01, -2.89556656e+00],
       [-7.31909949e-01, -1.49918113e+00],
       [ 5.83295445e-01, -1.88809011e+00],
       [-2.02285355e+00, -2.55138430e-01],
       [ 4.80877084e-01, -2.84586996e+00],
       [ 6.01969744e-01, -2.82576425e+00],
       [ 3.77513166e-02, -2.99638025e+00],
       [ 2.

In [85]:
X2

array([[ 2.60008654e+00,  3.60431467e+00],
       [ 2.08724513e+00,  2.93046749e+00],
       [ 1.71921827e+00,  1.00849765e+00],
       [ 3.23762965e+00,  1.97617106e+00],
       [ 9.38879571e-01,  2.83377011e+00],
       [-6.45759750e-01,  1.56239957e+00],
       [ 1.75304544e+00,  1.50871566e+00],
       [ 1.19355075e+00,  3.40083029e+00],
       [ 2.20366846e+00,  2.65673075e-01],
       [ 1.67774643e+00,  2.52795459e+00],
       [ 9.26300319e-01,  3.47123358e+00],
       [-9.87164701e-01,  2.07411905e+00],
       [ 8.89672774e-01,  3.11720368e+00],
       [ 6.79963167e-01,  3.57639470e+00],
       [ 1.41311667e+00,  2.76263939e-03],
       [ 9.37601703e-01,  2.11417908e+00],
       [ 2.59838457e+00,  2.15511251e+00],
       [ 3.57311202e+00,  3.63698817e+00],
       [ 2.28062722e+00,  1.56782300e+00],
       [ 2.90159399e+00,  9.92755861e-01],
       [ 2.49330160e+00,  3.41665279e+00],
       [ 3.54275075e+00,  1.13410617e+00],
       [ 1.94456020e+00,  2.88588244e+00],
       [ 2.

In [86]:
X3,X3.shape

(array([[-2.98076251e+00,  3.05999048e+00],
        [-2.28037062e+00,  1.94795286e+00],
        [-2.86562449e+00,  3.48431054e+00],
        [-2.12695188e+00,  2.79021968e+00],
        [-1.71025281e+00, -6.51890183e-01],
        [-2.87021705e+00, -3.52823674e-01],
        [-3.05499545e+00,  3.53957599e+00],
        [-1.97515690e+00,  1.83215877e+00],
        [-2.48224399e+00,  4.02495751e-01],
        [-1.02351278e+00,  1.88650404e+00],
        [-3.32656838e+00,  1.19194856e+00],
        [-1.01960260e+00,  1.03600359e+00],
        [-2.39901512e+00,  1.23525592e+00],
        [-3.06088277e+00,  1.88748098e-01],
        [-9.73400514e-01,  1.61863574e+00],
        [-1.18802002e+00,  1.19870674e+00],
        [-1.10940774e+00,  3.15621516e+00],
        [-3.66096361e+00, -1.05791345e+00],
        [-2.40914822e+00,  2.78292704e+00],
        [-1.52658105e+00, -2.07910273e-01],
        [-3.21896690e+00,  3.61639045e+00],
        [-2.97160747e+00,  3.66207804e-01],
        [-3.51408237e+00,  3.772

In [87]:
X

array([[-0.33715671, -1.01455774],
       [-2.68207788, -1.17953569],
       [-0.06440257, -1.92132449],
       ...,
       [-1.7044153 , -0.48953451],
       [-0.4804663 ,  3.37127751],
       [-2.93665707,  2.04216375]])

In [88]:
X.shape

(1500, 2)

In [89]:
Y = np.array([0]*Nclass+[1]*Nclass+[2]*Nclass)

In [90]:
Y

array([0, 0, 0, ..., 2, 2, 2])

In [91]:
Y.shape

(1500,)

In [92]:
#plt.scatter(X[:,0],X[:,1],c = Y,s=100, alpha=0.5)
#plt.show()


In [93]:
D = 2 # dimensions
M = 3 # Hidden layers
K = 3 # output classes

In [94]:
w1 = np.random.randn(D,M) #weight for hidden layer
b1 = np.random.randn(M) # bias for hidden layer
w2 = np.random.randn(M,K) #weight for output layer
b2 = np.random.randn(K) # bias for output layer

In [95]:
print(w1)
print(b1)
print(w2)
print(b2)

[[-0.90606156  1.39023079  0.03111528]
 [ 1.08307336 -0.85078225  0.86166517]]
[-0.28933525  2.6621672   1.8866588 ]
[[ 0.10774686  0.64137089  0.45105919]
 [-1.44737034 -1.49090281 -0.1296793 ]
 [ 1.66935085  0.21510884 -1.19274008]]
[-0.95984482  1.39960407 -0.12849129]


In [47]:
def sigmoid(a):
    return 1/(1+np.exp(-a))

In [61]:
def forward(X,w1,b1,w2,b2):
    c = X.dot(w1)+b1
    #print(c)
    Z = sigmoid(c) #sigmoid
    #print(Z)
    Z1 = np.tanh(c) #tanh
    Z2 = np.maximum(c,0) # ReLu
    A = Z.dot(w2)+b2 #output layer
    expA = np.exp(A) #exponential values for A
    Y = expA/expA.sum(axis = 1,keepdims = True) #probabilities for all values to get value 1(softmax) after adding every row values
    #print(Y.shape)
    return Y # softmax values

In [62]:
forward(X,w1,b1,w2,b2)

array([[0.18938003, 0.01633513, 0.79428484],
       [0.17556634, 0.01333626, 0.81109741],
       [0.12381016, 0.0074052 , 0.86878464],
       ...,
       [0.40374896, 0.10835196, 0.48789908],
       [0.48490737, 0.19446777, 0.32062486],
       [0.50225658, 0.20427029, 0.29347313]])

In [63]:
#classification rate
def classification_rate(Y,P):
    n_correct = 0
    n_total = 0
    for i in range(len(Y)):
        n_total += 1
        if Y[i] == P[i]:
            n_correct += 1
    return float(n_correct)/n_total        

In [64]:
P_Y_X = forward(X,w1,b1,w2,b2)

In [65]:
P_Y_X

array([[0.18938003, 0.01633513, 0.79428484],
       [0.17556634, 0.01333626, 0.81109741],
       [0.12381016, 0.0074052 , 0.86878464],
       ...,
       [0.40374896, 0.10835196, 0.48789908],
       [0.48490737, 0.19446777, 0.32062486],
       [0.50225658, 0.20427029, 0.29347313]])

In [69]:
P_Y_X.shape

(1500, 3)

In [73]:
P = np.argmax(P_Y_X,axis = 1) #prints the highest value index in row like 0,1,2

In [74]:
P

array([2, 2, 2, ..., 2, 0, 0], dtype=int64)

In [75]:
P.shape

(1500,)

In [77]:
assert(len(P)==len(Y))

In [78]:
print(classification_rate(Y,P))

0.13
