In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)

In [3]:
a

array([-0.29466567,  0.11176251,  0.46392022, -1.36657493,  0.37691849])

In [4]:
expa = np.exp(a) # exponential values for value A

In [5]:
expa

array([0.74478055, 1.11824726, 1.5902961 , 0.25497879, 1.45778549])

In [13]:
output = expa/expa.sum() # softmax formula 
output1 = expa/np.sum(expa) # another type

In [14]:
output1

array([0.14416722, 0.21645919, 0.30783371, 0.04935626, 0.28218362])

In [11]:
output #probabilities for softmax values

array([0.14416722, 0.21645919, 0.30783371, 0.04935626, 0.28218362])

In [12]:
output.sum() # adding all probabilities to get value 1 

1.0

# Another Example


In [15]:
A = np.random.randn(100,5)

In [16]:
A

array([[ 1.38063472,  1.08832484, -0.75479874, -2.73888611,  1.42298982],
       [ 0.31369359, -0.41831471,  2.39531859, -1.13631903, -0.43574716],
       [-1.77790063, -0.82205156, -0.01151988,  0.65947049,  0.21455141],
       [ 0.17389444,  0.97128389, -0.32124539, -1.43104788, -0.36669857],
       [ 0.40689858, -0.09144652,  0.6272376 , -0.01803307, -0.66698338],
       [ 1.15743905,  0.52812859,  0.62059901, -1.27358847,  1.06399733],
       [-1.21102146, -1.70027582, -0.77701165,  0.24832167,  0.04717403],
       [-0.724225  ,  1.60728274, -2.01631646, -0.64844773, -0.1729554 ],
       [-0.7117021 ,  0.38394621,  0.21607971, -1.80604206, -0.31505912],
       [-1.13651207,  1.36442499, -1.26447888, -0.27115114,  0.17032473],
       [-1.30031587, -0.4544291 , -1.03608802,  1.33556235,  0.89518486],
       [-1.03157285, -1.02998728,  1.12661946, -1.60110221,  1.65190876],
       [ 0.14542558, -0.86020035,  0.48155338, -0.99162497, -1.75081368],
       [-0.71986237,  0.6899425 , -0.1

In [17]:
expA = np.exp(A) #exponential values for A

In [18]:
expA

array([[ 3.9774254 ,  2.96929585,  0.47010522,  0.06464231,  4.1495082 ],
       [ 1.36847035,  0.65815507, 10.97169301,  0.32099843,  0.64678124],
       [ 0.16899255,  0.43952901,  0.98854622,  1.93376811,  1.23930583],
       [ 1.18992995,  2.64133346,  0.72524526,  0.23905829,  0.69301851],
       [ 1.50215175,  0.91261012,  1.87243102,  0.98212856,  0.51325454],
       [ 3.18177447,  1.69575588,  1.86004189,  0.27982567,  2.89793185],
       [ 0.29789284,  0.18263314,  0.45977794,  1.2818722 ,  1.04830443],
       [ 0.48470006,  4.98923572,  0.13314501,  0.52285676,  0.84117513],
       [ 0.49080808,  1.46806647,  1.24120131,  0.16430315,  0.72974573],
       [ 0.32093648,  3.91347213,  0.28238641,  0.76250124,  1.18568982],
       [ 0.27244572,  0.63481027,  0.3548401 ,  3.80213348,  2.44778825],
       [ 0.35644588,  0.3570115 ,  3.08520917,  0.20167411,  5.21692817],
       [ 1.15653166,  0.42307731,  1.61858674,  0.37097338,  0.1736326 ],
       [ 0.48681925,  1.9936009 ,  0.8

In [19]:
answer = expA/np.sum(expA)

In [20]:
answer

array([[4.94334025e-03, 3.69038718e-03, 5.84269926e-04, 8.03406497e-05,
        5.15721324e-03],
       [1.70080238e-03, 8.17987544e-04, 1.36361607e-02, 3.98952670e-04,
        8.03851588e-04],
       [2.10032271e-04, 5.46268305e-04, 1.22861395e-03, 2.40338229e-03,
        1.54027035e-03],
       [1.47890357e-03, 3.28277936e-03, 9.01370540e-04, 2.97113418e-04,
        8.61317547e-04],
       [1.86694820e-03, 1.13423683e-03, 2.32714953e-03, 1.22063776e-03,
        6.37898028e-04],
       [3.95446608e-03, 2.10756896e-03, 2.31175171e-03, 3.47781131e-04,
        3.60169249e-03],
       [3.70235896e-04, 2.26985468e-04, 5.71434673e-04, 1.59317393e-03,
        1.30288439e-03],
       [6.02409122e-04, 6.20086798e-03, 1.65479176e-04, 6.49832146e-04,
        1.04545389e-03],
       [6.10000466e-04, 1.82458534e-03, 1.54262615e-03, 2.04204055e-04,
        9.06963947e-04],
       [3.98875665e-04, 4.86385598e-03, 3.50963748e-04, 9.47674113e-04,
        1.47363373e-03],
       [3.38608965e-04, 7.8897

In [21]:
answer.sum()

1.0

In [23]:
ans = expA/expA.sum(axis = 1,keepdims = True)

In [24]:
ans

array([[0.3419683 , 0.25529204, 0.04041838, 0.00555777, 0.35676351],
       [0.09798516, 0.04712519, 0.78559473, 0.02298412, 0.0463108 ],
       [0.03542716, 0.09214171, 0.20723624, 0.40539008, 0.25980482],
       [0.21680084, 0.4812412 , 0.13213701, 0.04355554, 0.12626541],
       [0.25977207, 0.15782069, 0.32380569, 0.16984274, 0.08875881],
       [0.32089447, 0.17102365, 0.18759254, 0.02822152, 0.29226782],
       [0.09108534, 0.05584291, 0.14058421, 0.39195225, 0.32053529],
       [0.0695298 , 0.71570149, 0.01909953, 0.07500334, 0.12066583],
       [0.11988108, 0.35857883, 0.30316646, 0.04013145, 0.17824218],
       [0.04964225, 0.60533342, 0.04367935, 0.11794321, 0.18340176],
       [0.03626798, 0.08450596, 0.04723632, 0.5061401 , 0.32584963],
       [0.03867153, 0.03873289, 0.33472054, 0.02188003, 0.56599501],
       [0.30900159, 0.1130376 , 0.43245325, 0.09911649, 0.04639108],
       [0.11144541, 0.45638635, 0.19144228, 0.10776644, 0.13295952],
       [0.02042239, 0.20740061, 0.

In [25]:
ans.sum(axis = 1) #all column values are adding to get value 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
ans.shape

(100, 5)

In [26]:
expA.sum(axis = 1,keepdims = True)

array([[11.63097698],
       [13.96609811],
       [ 4.77014173],
       [ 5.48858546],
       [ 5.78257599],
       [ 9.91532977],
       [ 3.27048055],
       [ 6.97111269],
       [ 4.09412474],
       [ 6.46498609],
       [ 7.51201783],
       [ 9.21726883],
       [ 3.74280169],
       [ 4.36823081],
       [ 2.31208258],
       [ 3.54205024],
       [ 3.1655454 ],
       [ 5.51055163],
       [ 9.5250858 ],
       [ 9.09405678],
       [ 5.58018456],
       [ 6.23063556],
       [13.52624911],
       [ 3.03681056],
       [ 8.31754202],
       [16.53312706],
       [22.97150693],
       [ 4.1237954 ],
       [ 5.9689223 ],
       [ 3.44092895],
       [ 4.16174942],
       [14.83842421],
       [ 3.18518703],
       [15.28684707],
       [ 3.18392193],
       [11.52453704],
       [12.12137258],
       [ 6.37935667],
       [ 5.68187043],
       [19.79165669],
       [ 5.31502146],
       [ 3.37652474],
       [11.13762952],
       [ 5.16789732],
       [ 5.55793774],
       [ 9

In [27]:
expA.sum(axis = 1,keepdims = True).shape

(100, 1)